apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: cluster-mgmt
spec:
  releaseName: nginx-ingress
  chart:
    git: https://github.com/kubernetes/ingress-nginx.git
    path: charts/ingress-nginx
    ref: master
  values:
    replicaCount: 3